
package org.example.soap;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BusPassService", targetNamespace = "http://soap.squash.hccis.ca/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BusPassService {


    /**
     * 
     * @param arg0
     * @return
     *     returns org.example.soap.BusPass
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBusPass", targetNamespace = "http://soap.squash.hccis.ca/", className = "org.example.soap.GetBusPass")
    @ResponseWrapper(localName = "getBusPassResponse", targetNamespace = "http://soap.squash.hccis.ca/", className = "org.example.soap.GetBusPassResponse")
    @Action(input = "http://soap.squash.hccis.ca/BusPassService/getBusPassRequest", output = "http://soap.squash.hccis.ca/BusPassService/getBusPassResponse")
    public BusPass getBusPass(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns java.util.List<org.example.soap.BusPass>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBusPasses", targetNamespace = "http://soap.squash.hccis.ca/", className = "org.example.soap.GetBusPasses")
    @ResponseWrapper(localName = "getBusPassesResponse", targetNamespace = "http://soap.squash.hccis.ca/", className = "org.example.soap.GetBusPassesResponse")
    @Action(input = "http://soap.squash.hccis.ca/BusPassService/getBusPassesRequest", output = "http://soap.squash.hccis.ca/BusPassService/getBusPassesResponse")
    public List<BusPass> getBusPasses();

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCount", targetNamespace = "http://soap.squash.hccis.ca/", className = "org.example.soap.GetCount")
    @ResponseWrapper(localName = "getCountResponse", targetNamespace = "http://soap.squash.hccis.ca/", className = "org.example.soap.GetCountResponse")
    @Action(input = "http://soap.squash.hccis.ca/BusPassService/getCountRequest", output = "http://soap.squash.hccis.ca/BusPassService/getCountResponse")
    public int getCount();

}
