
package org.example.soapsquash;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SkillsAssessmentSquashTechnicalService", targetNamespace = "http://soap.squash.hccis.ca/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SkillsAssessmentSquashTechnicalService {


    /**
     * 
     * @return
     *     returns java.util.List<org.example.soapsquash.SkillsAssessmentSquashTechnical>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAssessments", targetNamespace = "http://soap.squash.hccis.ca/", className = "org.example.soapsquash.GetAssessments")
    @ResponseWrapper(localName = "getAssessmentsResponse", targetNamespace = "http://soap.squash.hccis.ca/", className = "org.example.soapsquash.GetAssessmentsResponse")
    @Action(input = "http://soap.squash.hccis.ca/SkillsAssessmentSquashTechnicalService/getAssessmentsRequest", output = "http://soap.squash.hccis.ca/SkillsAssessmentSquashTechnicalService/getAssessmentsResponse")
    public List<SkillsAssessmentSquashTechnical> getAssessments();

}
