
package org.example.soapsquash;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SkillsAssessmentSquashTechnicalServiceImplService", targetNamespace = "http://soap.squash.hccis.ca/", wsdlLocation = "http://10.4.33.51:8083/skillsassessmentsquashtechnicalservice?wsdl")
public class SkillsAssessmentSquashTechnicalServiceImplService
    extends Service
{

    private final static URL SKILLSASSESSMENTSQUASHTECHNICALSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SKILLSASSESSMENTSQUASHTECHNICALSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName SKILLSASSESSMENTSQUASHTECHNICALSERVICEIMPLSERVICE_QNAME = new QName("http://soap.squash.hccis.ca/", "SkillsAssessmentSquashTechnicalServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.4.33.51:8083/skillsassessmentsquashtechnicalservice?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SKILLSASSESSMENTSQUASHTECHNICALSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        SKILLSASSESSMENTSQUASHTECHNICALSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public SkillsAssessmentSquashTechnicalServiceImplService() {
        super(__getWsdlLocation(), SKILLSASSESSMENTSQUASHTECHNICALSERVICEIMPLSERVICE_QNAME);
    }

    public SkillsAssessmentSquashTechnicalServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SKILLSASSESSMENTSQUASHTECHNICALSERVICEIMPLSERVICE_QNAME, features);
    }

    public SkillsAssessmentSquashTechnicalServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SKILLSASSESSMENTSQUASHTECHNICALSERVICEIMPLSERVICE_QNAME);
    }

    public SkillsAssessmentSquashTechnicalServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SKILLSASSESSMENTSQUASHTECHNICALSERVICEIMPLSERVICE_QNAME, features);
    }

    public SkillsAssessmentSquashTechnicalServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SkillsAssessmentSquashTechnicalServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SkillsAssessmentSquashTechnicalService
     */
    @WebEndpoint(name = "SkillsAssessmentSquashTechnicalServiceImplPort")
    public SkillsAssessmentSquashTechnicalService getSkillsAssessmentSquashTechnicalServiceImplPort() {
        return super.getPort(new QName("http://soap.squash.hccis.ca/", "SkillsAssessmentSquashTechnicalServiceImplPort"), SkillsAssessmentSquashTechnicalService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SkillsAssessmentSquashTechnicalService
     */
    @WebEndpoint(name = "SkillsAssessmentSquashTechnicalServiceImplPort")
    public SkillsAssessmentSquashTechnicalService getSkillsAssessmentSquashTechnicalServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.squash.hccis.ca/", "SkillsAssessmentSquashTechnicalServiceImplPort"), SkillsAssessmentSquashTechnicalService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SKILLSASSESSMENTSQUASHTECHNICALSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw SKILLSASSESSMENTSQUASHTECHNICALSERVICEIMPLSERVICE_EXCEPTION;
        }
        return SKILLSASSESSMENTSQUASHTECHNICALSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
