
package org.example.soaprecord;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RecordSaleServiceSOAP", targetNamespace = "http://soap.recordstore.hccis.info/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RecordSaleServiceSOAP {


    /**
     * 
     * @return
     *     returns java.util.List<org.example.soaprecord.ArtistSaleList>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllSales", targetNamespace = "http://soap.recordstore.hccis.info/", className = "org.example.soaprecord.GetAllSales")
    @ResponseWrapper(localName = "getAllSalesResponse", targetNamespace = "http://soap.recordstore.hccis.info/", className = "org.example.soaprecord.GetAllSalesResponse")
    @Action(input = "http://soap.recordstore.hccis.info/RecordSaleServiceSOAP/getAllSalesRequest", output = "http://soap.recordstore.hccis.info/RecordSaleServiceSOAP/getAllSalesResponse")
    public List<ArtistSaleList> getAllSales();

    /**
     * 
     * @param arg0
     * @return
     *     returns org.example.soaprecord.ArtistSaleList
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSaleById", targetNamespace = "http://soap.recordstore.hccis.info/", className = "org.example.soaprecord.GetSaleById")
    @ResponseWrapper(localName = "getSaleByIdResponse", targetNamespace = "http://soap.recordstore.hccis.info/", className = "org.example.soaprecord.GetSaleByIdResponse")
    @Action(input = "http://soap.recordstore.hccis.info/RecordSaleServiceSOAP/getSaleByIdRequest", output = "http://soap.recordstore.hccis.info/RecordSaleServiceSOAP/getSaleByIdResponse")
    public ArtistSaleList getSaleById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns java.util.List<org.example.soaprecord.ArtistSaleList>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTransactions", targetNamespace = "http://soap.recordstore.hccis.info/", className = "org.example.soaprecord.GetTransactions")
    @ResponseWrapper(localName = "getTransactionsResponse", targetNamespace = "http://soap.recordstore.hccis.info/", className = "org.example.soaprecord.GetTransactionsResponse")
    @Action(input = "http://soap.recordstore.hccis.info/RecordSaleServiceSOAP/getTransactionsRequest", output = "http://soap.recordstore.hccis.info/RecordSaleServiceSOAP/getTransactionsResponse")
    public List<ArtistSaleList> getTransactions();

}
