
package org.example.soaprecord;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RecordSaleServiceSOAPImplService", targetNamespace = "http://www.hccis.info/recordstore", wsdlLocation = "http://localhost:8083/recordsalesoapservice?wsdl")
public class RecordSaleServiceSOAPImplService
    extends Service
{

    private final static URL RECORDSALESERVICESOAPIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException RECORDSALESERVICESOAPIMPLSERVICE_EXCEPTION;
    private final static QName RECORDSALESERVICESOAPIMPLSERVICE_QNAME = new QName("http://www.hccis.info/recordstore", "RecordSaleServiceSOAPImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8083/recordsalesoapservice?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RECORDSALESERVICESOAPIMPLSERVICE_WSDL_LOCATION = url;
        RECORDSALESERVICESOAPIMPLSERVICE_EXCEPTION = e;
    }

    public RecordSaleServiceSOAPImplService() {
        super(__getWsdlLocation(), RECORDSALESERVICESOAPIMPLSERVICE_QNAME);
    }

    public RecordSaleServiceSOAPImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RECORDSALESERVICESOAPIMPLSERVICE_QNAME, features);
    }

    public RecordSaleServiceSOAPImplService(URL wsdlLocation) {
        super(wsdlLocation, RECORDSALESERVICESOAPIMPLSERVICE_QNAME);
    }

    public RecordSaleServiceSOAPImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RECORDSALESERVICESOAPIMPLSERVICE_QNAME, features);
    }

    public RecordSaleServiceSOAPImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RecordSaleServiceSOAPImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RecordSaleServiceSOAP
     */
    @WebEndpoint(name = "RecordSaleServiceSOAPImplPort")
    public RecordSaleServiceSOAP getRecordSaleServiceSOAPImplPort() {
        return super.getPort(new QName("http://www.hccis.info/recordstore", "RecordSaleServiceSOAPImplPort"), RecordSaleServiceSOAP.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RecordSaleServiceSOAP
     */
    @WebEndpoint(name = "RecordSaleServiceSOAPImplPort")
    public RecordSaleServiceSOAP getRecordSaleServiceSOAPImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.hccis.info/recordstore", "RecordSaleServiceSOAPImplPort"), RecordSaleServiceSOAP.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RECORDSALESERVICESOAPIMPLSERVICE_EXCEPTION!= null) {
            throw RECORDSALESERVICESOAPIMPLSERVICE_EXCEPTION;
        }
        return RECORDSALESERVICESOAPIMPLSERVICE_WSDL_LOCATION;
    }

}
